@AppFirst_HostAddress = http://localhost:5091

###
GET {{AppFirst_HostAddress}}/tasks
Accept: application/json


### 
GET {{AppFirst_HostAddress}}/tasks/1
Accept: application/json


### 
POST {{AppFirst_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "задача 1",
  "isCompleted": false
}


### 
PUT {{AppFirst_HostAddress}}/tasks/2
Content-Type: application/json

{
  "title": "задача 2 update",
  "isCompleted": true
}


### 
DELETE {{AppFirst_HostAddress}}/tasks/1
